RR/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('Shopping.urls'))
]

Shopping/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('add_items',views.add_item),
    path('',views.list_view, name = 'home'),
    path('<person>/<slug:item_name>/<id>/update', views.update_view,name = 'update'),
    path('<person>/<slug:item_name>/<id>/delete', views.delete_view, name='delete'),
]

accounts/urls.py
from django.urls import path,include
from . import views


urlpatterns = [
    path('sign_up',views.sign_up),
    path('',include('django.contrib.auth.urls'))
]

Shopping/models.py
from django.db import models
from django.contrib.auth.models import User

status = [('Pending', 'Pending'), ('Bought', 'Bought'), ('Not Available', 'Not Available')]


class Shopping_list(models.Model):
    item_name = models.CharField(max_length=500)
    item_quantity = models.CharField(max_length=100)
    item_status = models.CharField(max_length=100, choices=status)
    date = models.DateField()
    person = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.person.username

    class Meta:
        verbose_name = 'Shopping list'
        verbose_name_plural = 'Shopping list'

accounts/models.py
from django.db import models

# Create your models here.

Shopping/forms.py
from django import forms
from . import models
from .models import status


class Add_items(forms.ModelForm):
    class Meta:
        model = models.Shopping_list
        fields = ['item_name', 'item_quantity', 'item_status', 'date','person']


class Update_items(forms.ModelForm):
    class Meta:
        model = models.Shopping_list
        exclude = ['person']


class DateFilter(forms.Form):
    date = forms.DateField()


class Add_items_form(forms.Form):
    name = forms.CharField(max_length=500)
    quantity = forms.CharField(max_length=500)
    status = forms.ChoiceField(choices=status)
    date = forms.DateField()

Shopping/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from . import forms, models
from django.shortcuts import (get_object_or_404,
                              render,
                              HttpResponseRedirect)



@login_required
def add_item(request):
    form = forms.Add_items_form(request.POST)
    model = models.Shopping_list
    if request.method == 'POST':
        if form.is_valid():
            name = form.cleaned_data['name']
            quantity = form.cleaned_data['quantity']
            status = form.cleaned_data['status']
            date_f = form.cleaned_data['date']
            p = model(item_name=name,item_quantity=quantity,item_status=status,date=date_f,person=request.user)
            p.save()
            return HttpResponseRedirect("/")
        else:
            print('invalid')
    return render(request, 'add_item.html', {'form':form})


@login_required
def list_view(request):
    dataset = models.Shopping_list.objects.all().filter(person=request.user).order_by('date')
    dataset = dataset.reverse()

    form = forms.DateFilter(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            d = form.cleaned_data['date']
            dataset = models.Shopping_list.objects.all().filter(person=request.user).filter(date=d)

        else:
            print('invalid')
    context = {"dataset":dataset,'form':form}
    return render(request, "index.html", context)


@login_required
def update_view(request,person,item_name,id):

    context = {}
    obj = get_object_or_404(models.Shopping_list, id=id)
    print(type(obj))
    form = forms.Update_items(request.POST or None, instance=obj)
    if (obj.person!=request.user):
        return HttpResponse('You are not authorised')

    if form.is_valid():
        form.save()
        return HttpResponseRedirect("/")

    context= {"form":form,"obj":obj}
    return render(request, "update_item.html", context)


@login_required
def delete_view(request,person,item_name,id):
    context = {}
    obj = get_object_or_404(models.Shopping_list, id=id)

    if (obj.person!=request.user):
        return HttpResponse('You are not authorised')

    if request.method == "POST":
        # delete object
        obj.delete()

        return HttpResponseRedirect("/")

    return render(request, "delete_view.html", context)

accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.
def sign_up(request):
    context = {}
    form = UserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            login(request,user)
            return render(request,'index.html')
    context['form']=form
    return render(request,'signup.html',context)

templates/add_item.html
<html>
{% load static %}
{% load crispy_forms_tags %}
    <head>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Update item</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
         <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <style >
            .form-control{

            }
            label{
                margin-top: 30px;
                font-size: 20px;
                color: grey;
            }
        </style>
    </head>
    <body>
<h1>User : {{ user }}</h1>
        <div class="container mt-5">
            <!-- top -->

            </div>
            <!-- // top -->
            <!-- Grocery Cards -->
            <div class="container">
               <form method="POST" >


    {% csrf_token %}
{# <div class="form-group">#}
{##}
{#                   <label >Item name</label>#}
{#    <input class="form-control form-control-lg" type="text" placeholder="Item name" name="item_name" id="example1">#}
{# <label >Item quantity</label>#}
{#     <input class="form-control form-control-lg" type="text" placeholder="Item quantity" name="item_quantity">#}
{#     <label >Item status</label>#}
{#     <select class="form-control form-control-lg" name="item_status">#}
{##}
{#                        <option value="Pending"> Pending</option>#}
{#                        <option value="Bought"> Bought</option>#}
{#                        <option value="Not Available"> Not Available</option>#}
{#                    </select>#}
{#     <label >Date</label>#}
{#                    <input class="form-control form-control-lg" type="date" placeholder="Date" name="date">#}
{##}
{#                    <input style="display: none" class="form-control form-control-lg" type="text" placeholder="Item name" name="person" value="{{ user.id }}" readonly>#}
{# </div>#}
                   {{ form|crispy }}
    <button type="submit" class="btn btn-primary mb-2">Add item</button>
</form>
            </div>
<script>
    $(document).ready(function() {
      $( function() {
    $( "#id_date" ).datepicker({
 maxDate:'0'
});
  } );
});
</script>
    </body>
</html>

templates/delete_view.html
<html>
{% load static %}
{% load crispy_forms_tags %}
    <head>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Delete</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">

</head>
<body>
<div class="container" style="margin: 100px auto">
    <h1 style="text-align: center"> Delete this item !!!</h1>
	<form method="POST">
		<!-- Security token by Django -->
		{% csrf_token %}
		Do you really want to delete this item ?
		<input class="btn btn-primary mb-2" type="submit" value="Yes" />
		<a href="/">Cancel </a>
	</form>
</div>

</body>
</html>

templates/form.html
<html>
{% load static %}
{% load crispy_forms_tags %}
    <head>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Update item</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
         <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <style >
            .form-control{

            }
            label{
                margin-top: 30px;
                font-size: 20px;
                color: grey;
            }
        </style>
    </head>
    <body>
<h1>User : {{ user }}</h1>
        <div class="container mt-5">
            <!-- top -->

            </div>
            <!-- // top -->
            <!-- Grocery Cards -->
            <div class="container">
               <form method="POST" >


    {% csrf_token %}
{# <div class="form-group">#}
{##}
{#                   <label >Item name</label>#}
{#    <input class="form-control form-control-lg" type="text" placeholder="Item name" name="item_name" id="example1">#}
{# <label >Item quantity</label>#}
{#     <input class="form-control form-control-lg" type="text" placeholder="Item quantity" name="item_quantity">#}
{#     <label >Item status</label>#}
{#     <select class="form-control form-control-lg" name="item_status">#}
{##}
{#                        <option value="Pending"> Pending</option>#}
{#                        <option value="Bought"> Bought</option>#}
{#                        <option value="Not Available"> Not Available</option>#}
{#                    </select>#}
{#     <label >Date</label>#}
{#                    <input class="form-control form-control-lg" type="date" placeholder="Date" name="date">#}
{##}
{#                    <input style="display: none" class="form-control form-control-lg" type="text" placeholder="Item name" name="person" value="{{ user.id }}" readonly>#}
{# </div>#}
                   {{ form|crispy }}
    <button type="submit" class="btn btn-primary mb-2">Add item</button>
</form>
            </div>
<script>
    $(document).ready(function() {
      $( function() {
    $( "#id_date" ).datepicker();
  } );
});
</script>
    </body>
</html>

templates/index.html
<html>
{% load static %}
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>View Grocery List</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
<div class="container header">
<h2 >User : {{ user }}</h2>
<a href="/accounts/logout"><h6>Logout</h6></a>
</div>
        <div class="container mt-5">
            <!-- top -->
            <div class="row">
                <div class="col-lg-6">
                    <h1>Grocery List</h1>
                    <p style="font-size: 22px"><a href="/add_items">Add items</a> </p>

                </div>
                <div class="col-lg-6 float-right">
                    <div class="row">
                        <form style="display: flex;width: 100%" method="post">
                        <div class="col-lg-8">
                            <!-- Date Filtering-->

                                {% csrf_token %}
                            <input type="date" class="form-control" name="date">


                        </div>

                        <div class="col-lg-4">
                            <button type="submit" class="btn btn-danger" > Filter</button>
                        </div>
                            </form>
                    </div>
                </div>
            </div>
            <!-- // top -->
            <!-- Grocery Cards -->
            <div class="row mt-4" >
                <!--- -->
                <!-- Loop This -->
                {% for data in dataset %}
                <div class="col-lg-4" style="margin-bottom: 50px">
                    <div class="card">
                        <div class="card-body">
                          <h5 class="card-title">{{ data.item_name}}</h5>
                          <h6 class="card-subtitle mb-2 text-muted">{{ data.item_quantity}} Pcs.</h6>
                          <p class="text-success">{{ data.item_status}}</p>
                            <a href="{% url 'update'  data.person data.item_name data.id %}">Update</a><br>
                            <a href="{% url 'delete'  data.person data.item_name data.id %}">Delete</a>
                            <h6 style="padding-top: 25px" class="card-subtitle mb-2 text-muted">Added on {{ data.date}} </h6>
                        </div>
                      </div>
                </div>
                <!-- // Loop -->
                {% endfor %}

            </div>
        </div>
    </body>
</html>

templates/signup.html
<html>
{% load static %}
{% load crispy_forms_tags %}
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<meta name="viewport" content="width=device-width, initial-scale=1.0">

        <title>Signup</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <meta charset="UTF-8">

</head>
<body>
<div class="container" style="margin: 100px auto">
    <h1 style="text-align: center">Sign Up Now</h1>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary mb-2">Login</button>
    <a style="display: block" href = "/accounts/login"> Already have account! Log in.</a>
  </form>
</div>
</body>
</html>

templates/update_item.html
<html>
{% load static %}
{% load crispy_forms_tags %}
    <head>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Update item</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
             <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <style >

        </style>
    </head>
    <body>
<h1>User : {{ user }}</h1>
        <div class="container mt-5">
            <!-- top -->

            </div>
            <!-- // top -->
            <!-- Grocery Cards -->
            <div class="container">
               <form method="POST" >

    <!-- Security token -->
    {% csrf_token %}

  {{ form|crispy }}
    <button type="submit" class="btn btn-primary mb-2">Update item</button>
</form>
            </div>
<script>
    $(document).ready(function() {
      $( function() {
    $( "#id_date" ).datepicker(
        {
 maxDate:'0'
}
    );
  } );
});
</script>
    </body>
</html>

templates/update_view.html
<html>
{% load static %}
{% load crispy_forms_tags %}
    <head>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Update item</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
             <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <style >

        </style>
    </head>
    <body>
<h1>User : {{ user }}</h1>
        <div class="container mt-5">
            <!-- top -->

            </div>
            <!-- // top -->
            <!-- Grocery Cards -->
            <div class="container">
               <form method="POST" >

    <!-- Security token -->
    {% csrf_token %}

  {{ form|crispy }}
    <button type="submit" class="btn btn-primary mb-2">Update item</button>
</form>
            </div>
<script>
    $(document).ready(function() {
      $( function() {
    $( "#id_date" ).datepicker();
  } );
});
</script>
    </body>
</html>